name       : ant-dracula-gtk-theme
version    : 4.0.0
release    : 10
source     :
    - https://github.com/dracula/gtk/archive/refs/tags/v4.0.0.tar.gz : 462f397f957d8443cfef7cddf5e6b92878c5aeef1af9f581307d43257279eb4c
homepage   : https://draculatheme.com/
license    : GPL-3.0-or-later
component  : desktop.theme
summary    : Dracula variant of the Ant Theme
description: |
    Dracula variant of the Ant Theme
rundeps    :
    - gtk2-engine-murrine
install    : |
    for dir in assets gnome-shell gtk-2.0 gtk-3.0 gtk-3.20 gtk-4.0 metacity-1; do
        for file in $(find ${dir} -type f); do
            install -Dm 00644 "$file" $installdir/usr/share/themes/Ant-Dracula/"$file"
        done
    done

    install -Dm 00644 index.theme $installdir/usr/share/themes/Ant-Dracula/index.theme

    # Create GTK2 symlinks
    for file in checkbox radio; do
        for state in unchecked checked mixed; do
            ln -sf ../../assets/$file-$state.png $installdir/usr/share/themes/Ant-Dracula/gtk-2.0/assets/$file-$state.png
            for substate in active hover insensitive; do
                ln -sf ../../assets/$file-$state-$substate.png $installdir/usr/share/themes/Ant-Dracula/gtk-2.0/assets/$file-$state-$substate.png
            done
        done
    done
