name       : ant-dracula-gtk-theme
version    : 3.0.0
release    : 7
source     :
    - https://github.com/dracula/gtk/releases/download/v3.0/Dracula.tar.xz : d0a7af0baab7c2ec4ed138c7ee1e4558450154ee4b9a5545e7525d022a79d261
homepage   : https://draculatheme.com/
license    : GPL-3.0-or-later
component  : desktop.themes
summary    : Dracula variant of the Ant Theme
description: |
    Dracula variant of the Ant Theme
rundeps    :
    - gtk2-engine-murrine
install    : |
    for dir in assets gnome-shell gtk-2.0 gtk-3.0 gtk-3.20 gtk-4.0 metacity-1; do
        for file in $(find ${dir} -type f); do
            install -Dm 00644 "$file" $installdir/usr/share/themes/Ant-Dracula/"$file"
        done
    done

    install -Dm 00644 index.theme $installdir/usr/share/themes/Ant-Dracula/index.theme

    # Create GTK2 symlinks
    for file in checkbox radio; do
        for state in unchecked checked mixed; do
            ln -sf ../../assets/$file-$state.png $installdir/usr/share/themes/Ant-Dracula/gtk-2.0/assets/$file-$state.png
            for substate in active hover insensitive; do
                ln -sf ../../assets/$file-$state-$substate.png $installdir/usr/share/themes/Ant-Dracula/gtk-2.0/assets/$file-$state-$substate.png
            done
        done
    done
