name       : ant-dracula-gtk-theme
version    : 1.3.0
release    : 3
source     :
    - https://github.com/EliverLara/Ant-Dracula/archive/v1.3.0.tar.gz : 5de816ebdcdc5cccf02c8965bf7a38e0a9718a769e274505bcf3809d3ce6ece8
license    : GPL-3.0-or-later
component  : desktop.themes
summary    : Dracula variant of the Ant Theme
description: |
    Dracula variant of the Ant Theme
rundeps    :
    - gtk2-engine-murrine
install    : |
    for dir in assets gnome-shell gtk-2.0 gtk-3.0 gtk-3.20 metacity-1; do
        for file in $(find ${dir} -type f); do
            install -Dm 00644 "$file" $installdir/usr/share/themes/Ant-Dracula/"$file"
        done
    done

    install -Dm 00644 index.theme $installdir/usr/share/themes/Ant-Dracula/index.theme
