name       : ant-dracula-gtk-theme
version    : 1.1.0
release    : 1
source     :
    - https://github.com/EliverLara/Ant-Dracula/archive/v1.1.0.tar.gz : a441f1faa7c8c06257bb0c11aa3836f2ccf5acd735f8cab88886d96d10f717ba
license    : GPL-3.0
component  : desktop.themes
summary    : Dracula variant of the Ant Theme
description: |
    Dracula variant of the Ant Theme
rundeps    :
    - gtk2-engine-murrine
install    : |
    for dir in assets gnome-shell gtk-2.0 gtk-3.0 gtk-3.20 metacity-1; do
        for file in $(find ${dir} -type f); do
            install -Dm 00644 "$file" $installdir/usr/share/themes/Ant-Dracula/"$file"
        done
    done

    install -Dm 00644 index.theme $installdir/usr/share/themes/Ant-Dracula/index.theme
