name       : ant-dracula-gtk-theme
version    : 1.2.0
release    : 2
source     :
    - https://github.com/EliverLara/Ant-Dracula/archive/v1.2.0.tar.gz : 8f8336340eae4178f3f1b22d6c591342fbbe11d1d0d9159041ecb52818b25076
license    : GPL-3.0
component  : desktop.themes
summary    : Dracula variant of the Ant Theme
description: |
    Dracula variant of the Ant Theme
rundeps    :
    - gtk2-engine-murrine
install    : |
    for dir in assets gnome-shell gtk-2.0 gtk-3.0 gtk-3.20 metacity-1; do
        for file in $(find ${dir} -type f); do
            install -Dm 00644 "$file" $installdir/usr/share/themes/Ant-Dracula/"$file"
        done
    done

    install -Dm 00644 index.theme $installdir/usr/share/themes/Ant-Dracula/index.theme
